-- ============================================================
-- English Learning App — Supabase Schema
-- Run this in Supabase SQL Editor
-- ============================================================

-- Daily logs: one per study session
create table if not exists daily_logs (
  id          uuid primary key default gen_random_uuid(),
  date        date not null unique,
  week_number int not null default 1,
  topic       text,
  started_at  text,
  finished_at text,
  checklist   jsonb not null default '{
    "learned_10_words": false,
    "finished_writing": false,
    "wrote_journal": false,
    "reviewed_flashcards": false
  }',
  created_at  timestamptz not null default now()
);

-- Vocabulary entries: 10 per day, linked to a daily_log
create table if not exists vocabulary_entries (
  id              uuid primary key default gen_random_uuid(),
  log_id          uuid references daily_logs(id) on delete cascade,
  date            date not null,
  word            text not null,
  meaning         text not null,
  example_sentence text not null,        -- generated by Claude
  my_sentence     text default '',       -- user fills in
  week_number     int not null default 1,
  created_at      timestamptz not null default now()
);

-- Writing sessions: one per daily_log
create table if not exists writing_sessions (
  id           uuid primary key default gen_random_uuid(),
  log_id       uuid references daily_logs(id) on delete cascade,
  date         date not null unique,
  topic        text not null default '',
  content      text not null default '',
  new_words_used text[] default '{}',
  mini_journal text default '',
  self_review  jsonb not null default '{
    "vocabulary_correct": 0,
    "sentences_clear": 0,
    "thought_in_english": 0,
    "wrote_without_stopping": 0
  }',
  created_at   timestamptz not null default now()
);

-- Progress days: one row per day completed
create table if not exists progress_days (
  id           uuid primary key default gen_random_uuid(),
  date         date not null unique,
  completed    boolean not null default false,
  words_count  int not null default 0,
  writing_done boolean not null default false,
  created_at   timestamptz not null default now()
);

-- Indexes for fast queries
create index if not exists idx_vocabulary_entries_date on vocabulary_entries(date);
create index if not exists idx_vocabulary_entries_week on vocabulary_entries(week_number);
create index if not exists idx_progress_days_date on progress_days(date);

-- Row Level Security (optional — disable if no auth)
alter table daily_logs enable row level security;
alter table vocabulary_entries enable row level security;
alter table writing_sessions enable row level security;
alter table progress_days enable row level security;

-- Allow all for now (personal app, no auth)
create policy "allow all" on daily_logs for all using (true) with check (true);
create policy "allow all" on vocabulary_entries for all using (true) with check (true);
create policy "allow all" on writing_sessions for all using (true) with check (true);
create policy "allow all" on progress_days for all using (true) with check (true);
